baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Saleh Mehdikhani'
theme = 'hugo-coder'
defaultContentLanguage = "en"

[params]
  author = "Saleh Mehdikhani"
  info = ["Embedded Software Engineer"]
  description = "Personal website and resume"
  keywords = "blog,developer,resume"
  avatarURL = "images/saleh_cv.jpeg"
  dateFormat = "January 2, 2006"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Enter a link to your social media profiles here."

  hideCredits = false
  hideCopyright = false

  rtl = false

  math = true
  customCSS = []

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/saleh-mehdikhani"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/saleh-mehdikhani/"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 3
  url = "mailto:"

[languages.en]
  languageName = "English"

[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[languages.en.menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"

[[languages.en.menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"
