name: Build Resume PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            gnupg \
            ca-certificates \
            fonts-liberation \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils

      - name: Install npm dependencies
        run: npm install

      - name: Set Puppeteer environment
        run: echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false" >> $GITHUB_ENV

      - name: Run build script with no-sandbox
        run: |
          # Create a wrapper script for Chrome that adds --no-sandbox
          mkdir -p /tmp/chrome-wrapper
          cat > /tmp/chrome-wrapper/chrome << 'EOF'
          #!/bin/bash
          exec "$(dirname "$0")/chrome-original" --no-sandbox --disable-setuid-sandbox "$@"
          EOF
          chmod +x /tmp/chrome-wrapper/chrome
          
          # Find Chrome executable in Puppeteer
          CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())" 2>/dev/null || echo "")
          
          if [ -n "$CHROME_PATH" ] && [ -f "$CHROME_PATH" ]; then
            echo "Found Chrome at: $CHROME_PATH"
            CHROME_DIR=$(dirname "$CHROME_PATH")
            mv "$CHROME_PATH" "$CHROME_DIR/chrome-original"
            cp /tmp/chrome-wrapper/chrome "$CHROME_PATH"
            chmod +x "$CHROME_PATH"
            echo "Chrome wrapper installed"
          else
            echo "Chrome not found, running without wrapper"
          fi
          
          # Run the build script
          python3 build_resume.py

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: build/resume.pdf